# NOTE: Assertions have been autogenerated by utils/update_mca_test_checks.py
# RUN: llvm-mca -mtriple=mips64 -mcpu=r10000 -iterations=1 < %s | FileCheck %s

# One instruction of each kind the R10000 model distinguishes.
  lw      $2, 0($4)
  addu    $3, $2, $5
  sll     $6, $3, 2
  movn    $7, $6, $3
  mult    $6, $7
  mflo    $8
  dmultu  $8, $9
  divu    $zero, $8, $9
  ddiv    $zero, $10, $11
  sd      $9, 16($4)
  ldc1    $f24, 8($4)
  add.d   $f6, $f0, $f8
  cvt.s.w $f5, $f7
  cvt.d.s $f9, $f5
  mul.d   $f0, $f2, $f4
  madd.d  $f10, $f12, $f14, $f16
  div.s   $f18, $f20, $f22
  div.d   $f18, $f20, $f22
  sqrt.s  $f1, $f3
  sqrt.d  $f2, $f4
  mtc1    $2, $f26
  mfc1    $3, $f26

# CHECK:      Iterations:        1
# CHECK-NEXT: Instructions:      22
# CHECK-NEXT: Total Cycles:      121
# CHECK-NEXT: Total uOps:        22

# CHECK:      Dispatch Width:    4
# CHECK-NEXT: uOps Per Cycle:    0.18
# CHECK-NEXT: IPC:               0.18
# CHECK-NEXT: Block RThroughput: 115.0

# CHECK:      Instruction Info:
# CHECK-NEXT: [1]: #uOps
# CHECK-NEXT: [2]: Latency
# CHECK-NEXT: [3]: RThroughput
# CHECK-NEXT: [4]: MayLoad
# CHECK-NEXT: [5]: MayStore
# CHECK-NEXT: [6]: HasSideEffects (U)

# CHECK:      [1]    [2]    [3]    [4]    [5]    [6]    Instructions:
# CHECK-NEXT:  1      2     1.00    *                   lw	$2, 0($4)
# CHECK-NEXT:  1      1     0.50                        addu	$3, $2, $5
# CHECK-NEXT:  1      1     1.00                        sll	$6, $3, 2
# CHECK-NEXT:  1      1     1.00                        movn	$7, $6, $3
# CHECK-NEXT:  1      5     6.00                        mult	$6, $7
# CHECK-NEXT:  1      1     0.50                        mflo	$8
# CHECK-NEXT:  1      10    9.00                        dmultu	$8, $9
# CHECK-NEXT:  1      34    34.00                 U     divu	$zero, $8, $9
# CHECK-NEXT:  1      66    66.00                 U     ddiv	$zero, $10, $11
# CHECK-NEXT:  1      1     1.00           *            sd	$9, 16($4)
# CHECK-NEXT:  1      3     1.00    *                   ldc1	$f24, 8($4)
# CHECK-NEXT:  1      2     1.00                        add.d	$f6, $f0, $f8
# CHECK-NEXT:  1      4     2.00                        cvt.s.w	$f5, $f7
# CHECK-NEXT:  1      2     1.00                        cvt.d.s	$f9, $f5
# CHECK-NEXT:  1      2     1.00                        mul.d	$f0, $f2, $f4
# CHECK-NEXT:  1      4     1.00                        madd.d	$f10, $f12, $f14, $f16
# CHECK-NEXT:  1      12    14.00                       div.s	$f18, $f20, $f22
# CHECK-NEXT:  1      19    21.00                       div.d	$f18, $f20, $f22
# CHECK-NEXT:  1      18    20.00                       sqrt.s	$f1, $f3
# CHECK-NEXT:  1      33    35.00                       sqrt.d	$f2, $f4
# CHECK-NEXT:  1      3     1.00                        mtc1	$2, $f26
# CHECK-NEXT:  1      2     1.00                        mfc1	$3, $f26

# CHECK:      Resources:
# CHECK-NEXT: [0]   - R10KALU1
# CHECK-NEXT: [1]   - R10KALU2
# CHECK-NEXT: [2]   - R10KAddrQueue
# CHECK-NEXT: [3]   - R10KFPAdd
# CHECK-NEXT: [4]   - R10KFPDivSqrt
# CHECK-NEXT: [5]   - R10KFPMul
# CHECK-NEXT: [6.0] - R10KFPQueue
# CHECK-NEXT: [6.1] - R10KFPQueue
# CHECK-NEXT: [7.0] - R10KIntQueue
# CHECK-NEXT: [7.1] - R10KIntQueue
# CHECK-NEXT: [8]   - R10KLS
# CHECK-NEXT: [9]   - R10KMulDiv

# CHECK:      Resource pressure per iteration:
# CHECK-NEXT: [0]    [1]    [2]    [3]    [4]    [5]    [6.0]  [6.1]  [7.0]  [7.1]  [8]    [9]
# CHECK-NEXT: 3.00   5.00   3.00   7.00   90.00  6.00   7.00   6.00   3.00   3.00   3.00   115.00

# CHECK:      Resource pressure by instruction:
# CHECK-NEXT: [0]    [1]    [2]    [3]    [4]    [5]    [6.0]  [6.1]  [7.0]  [7.1]  [8]    [9]    Instructions:
# CHECK-NEXT:  -      -     1.00    -      -      -      -      -      -      -     1.00    -     lw	$2, 0($4)
# CHECK-NEXT:  -     1.00    -      -      -      -      -      -      -      -      -      -     addu	$3, $2, $5
# CHECK-NEXT: 1.00    -      -      -      -      -      -      -      -     1.00    -      -     sll	$6, $3, 2
# CHECK-NEXT: 1.00    -      -      -      -      -      -      -      -     1.00    -      -     movn	$7, $6, $3
# CHECK-NEXT:  -     1.00    -      -      -      -      -      -     1.00    -      -     6.00   mult	$6, $7
# CHECK-NEXT: 1.00    -      -      -      -      -      -      -      -      -      -      -     mflo	$8
# CHECK-NEXT:  -     1.00    -      -      -      -      -      -      -     1.00    -     9.00   dmultu	$8, $9
# CHECK-NEXT:  -     1.00    -      -      -      -      -      -     1.00    -      -     34.00  divu	$zero, $8, $9
# CHECK-NEXT:  -     1.00    -      -      -      -      -      -     1.00    -      -     66.00  ddiv	$zero, $10, $11
# CHECK-NEXT:  -      -     1.00    -      -      -      -      -      -      -     1.00    -     sd	$9, 16($4)
# CHECK-NEXT:  -      -     1.00    -      -      -      -      -      -      -     1.00    -     ldc1	$f24, 8($4)
# CHECK-NEXT:  -      -      -     1.00    -      -      -     1.00    -      -      -      -     add.d	$f6, $f0, $f8
# CHECK-NEXT:  -      -      -     2.00    -      -     2.00    -      -      -      -      -     cvt.s.w	$f5, $f7
# CHECK-NEXT:  -      -      -     1.00    -      -     1.00    -      -      -      -      -     cvt.d.s	$f9, $f5
# CHECK-NEXT:  -      -      -      -      -     1.00    -     1.00    -      -      -      -     mul.d	$f0, $f2, $f4
# CHECK-NEXT:  -      -      -     1.00    -     1.00   2.00    -      -      -      -      -     madd.d	$f10, $f12, $f14, $f16
# CHECK-NEXT:  -      -      -      -     14.00  1.00    -     1.00    -      -      -      -     div.s	$f18, $f20, $f22
# CHECK-NEXT:  -      -      -      -     21.00  1.00   1.00    -      -      -      -      -     div.d	$f18, $f20, $f22
# CHECK-NEXT:  -      -      -      -     20.00  1.00    -     1.00    -      -      -      -     sqrt.s	$f1, $f3
# CHECK-NEXT:  -      -      -      -     35.00  1.00   1.00    -      -      -      -      -     sqrt.d	$f2, $f4
# CHECK-NEXT:  -      -      -     1.00    -      -      -     1.00    -      -      -      -     mtc1	$2, $f26
# CHECK-NEXT:  -      -      -     1.00    -      -      -     1.00    -      -      -      -     mfc1	$3, $f26
